### PR TITLE
Implement a language server

### PR DESCRIPTION
**Pull request by fwcd**
Fixes N/A

### Description

Language servers provide features like inline error/warning diagnostics, code completion, hovers and more in an editor-agnostic way. (See [here](https://microsoft.github.io/language-server-protocol/) for details) Most notably, editors like VSCode can act as a client to provide these IDE-like features.

### Changes proposed in this pull request

- Implement a language server for clio in a new package (`language-server`)
- Add a new executable called `clio-language-server`
- VSCode support is implemented in https://github.com/clio-lang/vscode-clio/pull/3

### ToDo

- [x] Diagnostics based on compiler errors
- [x] Code completion
    - [x] Keywords
    - [x] Function names (very basic currently, non-context-aware)
- [x] Hovers (very basic currently, only presents tokens)

### Screenshots

image

image

### Notes

Note that these features are pretty limited currently, because the `clio-core` seems to parse and generate code in a single pass without emitting a lot of information about the parsed code from what I can tell. I haven't looked too deep into this, but if the compiler were to generate more extensive metadata e.g. emit a full AST, symbol tables, etc., then the language server could provide much richer language features too.

### CODE REVIEW

**Comment by garritfra** [comment]
Thanks for this! Is this ready for review?

**Comment by fwcd** [comment]
Yes, should be ready for review. The language server is still pretty basic, but should provide a good foundation to hack and improve on. :)

**Comment by pouya-eghbali** [comment]
@fwcd this looks amazing! Thanks for the great work! I will merge this into 0.8, after fixing the conflicts caused by the recent changes in the compiler.

**Comment by pouya-eghbali** [comment]
Ok, this is what I'm working on next. I just reviewed the code, we need to make a few changes here because I rewrote the parser / compiler, as far as I can see the only requirement is to export the parse function, the rest of this PR (the language-server package) can be merged as is. I'll start working on it first thing tomorrow morning! Thanks again @fwcd !

**Pull request merged**
