### PR TITLE
Move model into model.js

### PR DESCRIPTION
**Pull request by pouya-eghbali**
I moved `model` into a separate file as we discussed.

### CODE REVIEW

**Comment by garritfra** [comment]
Okay, now we can use the parsing error message in `compiler.js` again. Do you want to append a commit that implements that to this PR?

**Comment by pouya-eghbali** [comment]
Yeah, I'll do that. I'll make another little refactoring too, I'll move IO to io.js (currently in lazy.js)

**Comment by garritfra** [comment]
I think, given that the compiler is being integrated continually instead of incrementally, we can work on the 0.2 branch directly. We shouldnt run into any conflicts, because its mainly you who commits on this branch. Should I merge?

**Comment by pouya-eghbali** [comment]
Fair enough. Let's do that then

**Pull request merged**
