### PR TITLE
Turn log message more colorful

### LINKED ISSUE #52: Prettify CLI messages
I noticed that some CLI commands crash with an ugly error message when an incorrect filepath is provided. These crashes should be catched, handled and displayed as a human-friendly message:

- [x] `clio run`
- [x] `clio new`
- [x] `clio ast`
- [x] `clio highlight`
- [x] `clio compile`

EDIT: @andreyluiz noted, that the CLI could need some color in general. This will be part of this issue

### PR DESCRIPTION
**Pull request by andreyluiz**
Fixes #52 

This PR is intended to make our log messages more colorful.

I added colors for Error, Warning, Info and Success.

### CODE REVIEW

**Comment by garritfra** [comment]
The ´clio init´ command does not show colored messages. Will we keep this command? If so, we should add color to these messages as well

**Comment by garritfra** [comment]
Also, what do you think about renaming the colors file to `log`? We could then write `log.error()`. I think that looks more semantically correct

**Comment by pouya-eghbali** [comment]
@garritfra we'll not be able to merge this into v0.2.0, is there going to be a v0.1.7 before v0.2?

**Comment by garritfra** [comment]
Bildschirmfoto 2019-12-21 um 22 32 21

`clio run` command throws an error, whilst `clio highlight` points to the usage help. Should we make this more consistent?

**Comment by garritfra** [comment]
> @garritfra we'll not be able to merge this into v0.2.0, is there going to be a v0.1.7 before v0.2?

There are some changes that have not been published yet either. v0.1.7 would be a good idea👍

**Comment by andreyluiz** [comment]
@garritfra About `clio init` it just calls `getDependencies`. This was the only thing I didn't touch in regard of colored messages. These messages are output from the `getDependencies` function. Not by the cli, itself. Do you think I have to make these print `Info` messages too? On `clio new` the three initial lines are from the same `getDependencies` messages.

**Comment by andreyluiz** [comment]
> clio run command throws an error, whilst clio highlight points to the usage help. Should we make this more consistent?
@garritfra @pouya-eghbali  We have two options here. We can add to `clio highlight` a default, like there is on `clio run`. The default in this case is the main file of `clio.toml`. Or we can remove the default from `clio run` to let `yargs` complain about the missing parameter. What do you think?

**Comment by garritfra** [comment]
I'd like to be able to use `clio run` without any parameters if a main file is specified in clio.toml. If you want to _highlight_  something, I don't think you would expect to highlight the entry point by default. In my opinion, we should print the usage message in this case

**Comment by garritfra** [comment]
Regarding `clio init`: should we keep it's behavior for now? In the future, I think it would be nice for `clio new` and `clio init` to have a similar effect, just that the `new` command creates a new directory before initializing a project

**Comment by andreyluiz** [comment]
> I'd like to be able to use clio run without any parameters if a main file is specified in clio.toml. If you want to highlight something, I don't think you would expect to highlight the entry point by default. In my opinion, we should print the usage message in this case

So we don't need to change anything on this behalf. Right? 

> Regarding clio init: should we keep it's behavior for now? In the future, I think it would be nice for clio new and clio init to have a similar effect, just that the new command creates a new directory before initializing a project

Just to remember. We will have the new parser soon. I don't if these messages will be prompted with what is being made.

**Comment by garritfra** [comment]
> Just to remember. We will have the new parser soon. I'm not sure if these messages will be prompted with what is being made.

True. Let's merge this

**Pull request merged**
